version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      commitlint:
        patterns: ["@commitlint/*"]
      conventional-changelog:
        patterns: ["conventional-changelog", "conventional-changelog-*"]
      eslint:
        patterns: ["eslint", "@eslint/*"]
      eslint-dev:
        patterns: ["typescript-eslint", "eslint-*"]
      typescript:
        patterns: ["@tsconfig/*", "@types/*", "typescript"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      ybiquitous-actions:
        patterns: ["ybiquitous/.github/*"]
    cooldown:
      exclude: ["ybiquitous/.github/*"]
