version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      commitlint:
        patterns: ["@commitlint/*"]
      eslint-dev:
        patterns: ["@typescript-eslint/*", "eslint-*"]
      typescript:
        patterns: ["@tsconfig/*", "@types/*", "typescript"]
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
