language: node_js

node_js:
  - 10
  - 8

cache:
  yarn: true
  directories:
    - node_modules

script:
  - commitlint-travis
  - npm test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 8

notifications:
  email: false
