language: node_js

node_js:
  - 10
  - 8

cache:
  directories:
    - "$HOME/.npm"

before_install:
  # `npm ci` is available since npm@5.7.0
  - if ruby -e "exit(1) if Gem::Version.new(ARGV[0]) >= Gem::Version.new('5.7.0')" $(npm -v); then
      npm i -g npm@latest;
    fi

before_script:
  - commitlint-travis
  - npm run lint

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 8

notifications:
  email: false
