language: node_js

node_js:
  - 10
  - 8
  - 6

cache:
  yarn: true
  directories:
    - node_modules

script:
  - commitlint-travis
  - npm run build
  - npm test
  - npm run test:coverage

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 6

notifications:
  email: false
