language: node_js

node_js:
  - 8
  - 6

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - git fetch --unshallow

script:
  - commitlint --from=HEAD~1
  - npm run build
  - npm run lint
  - npm test

after_success:
  - if [[ $TRAVIS_NODE_VERSION = '8' ]]; then npm run test:coverage; fi

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 6

notifications:
  email: false
